// app/api/download/roommate/route.ts
// 방금 미리보기한 샘플 문서와 동일한 형식으로 생성합니다
import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const { summary, rules, agreement, tips } = await request.json()
    const {
      Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
      AlignmentType, BorderStyle, WidthType, ShadingType, VerticalAlign,
      Header, Footer, PageNumber,
    } = await import('docx')

    const today = new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' })
    const docNo = `JD-${Date.now().toString().slice(-6)}`
    const cb = { style: BorderStyle.SINGLE, size: 6, color: 'E2E8F0' }
    const ab = { top: cb, bottom: cb, left: cb, right: cb, insideH: cb, insideV: cb }
    const nb = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' }
    const nbs = { top: nb, bottom: nb, left: nb, right: nb }
    const blank = (s = 120) => new Paragraph({ children: [new TextRun('')], spacing: { before: s, after: s } })
    const sh = (t: string) => new Paragraph({ children: [new TextRun({ text: t, bold: true, size: 24, color: '1E3A5F', font: 'Malgun Gothic' })], border: { left: { style: BorderStyle.THICK, size: 20, color: '2563EB' } }, indent: { left: 180 }, spacing: { before: 360, after: 160 } })
    type DocChild = InstanceType<typeof Paragraph> | InstanceType<typeof Table>
    const ch: DocChild[] = []

    // 1. 로고 헤더
    ch.push(new Table({ width: { size: 9026, type: WidthType.DXA }, columnWidths: [6500, 2526], borders: { top: nb, bottom: { style: BorderStyle.SINGLE, size: 8, color: '2563EB' }, left: nb, right: nb, insideH: nb, insideV: nb }, rows: [new TableRow({ children: [new TableCell({ borders: nbs, width: { size: 6500, type: WidthType.DXA }, children: [new Paragraph({ children: [new TextRun({ text: '자 취 박 사', bold: true, size: 32, color: '2563EB', font: 'Malgun Gothic' })] }), new Paragraph({ children: [new TextRun({ text: 'JACHI DOCTOR  |  주거 생활 지원 서비스', size: 16, color: '94A3B8', font: 'Malgun Gothic' })] })] }), new TableCell({ borders: nbs, width: { size: 2526, type: WidthType.DXA }, verticalAlign: VerticalAlign.BOTTOM, children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: [new TextRun({ text: `문서번호: ${docNo}`, size: 17, color: '64748B', font: 'Malgun Gothic' })] }), new Paragraph({ alignment: AlignmentType.RIGHT, children: [new TextRun({ text: `작성일: ${today}`, size: 17, color: '64748B', font: 'Malgun Gothic' })] })] })] })] }), blank(300))

    // 2. 제목 박스
    ch.push(new Table({ width: { size: 9026, type: WidthType.DXA }, columnWidths: [9026], rows: [new TableRow({ children: [new TableCell({ borders: { top: cb, bottom: cb, left: { style: BorderStyle.THICK, size: 20, color: '2563EB' }, right: nb }, shading: { fill: 'EFF6FF', type: ShadingType.CLEAR }, margins: { top: 200, bottom: 200, left: 300, right: 300 }, width: { size: 9026, type: WidthType.DXA }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: '룸메이트 생활 협정서', bold: true, size: 40, color: '1E3A5F', font: 'Malgun Gothic' })] }), new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 60 }, children: [new TextRun({ text: 'Roommate Life Agreement', size: 20, color: '94A3B8', font: 'Malgun Gothic' })] })] })] })] }), blank(240))

    // 3. 기본 정보
    const ic = (l: string, v: string, w1: number, w2: number) => [new TableCell({ width: { size: w1, type: WidthType.DXA }, shading: { fill: 'F1F5F9', type: ShadingType.CLEAR }, borders: ab, margins: { top: 100, bottom: 100, left: 150, right: 150 }, children: [new Paragraph({ children: [new TextRun({ text: l, bold: true, size: 19, color: '475569', font: 'Malgun Gothic' })] })] }), new TableCell({ width: { size: w2, type: WidthType.DXA }, borders: ab, margins: { top: 100, bottom: 100, left: 150, right: 150 }, children: [new Paragraph({ children: [new TextRun({ text: v, size: 19, color: '1E293B', font: 'Malgun Gothic' })] })] })]
    ch.push(sh('■ 기본 정보'), new Table({ width: { size: 9026, type: WidthType.DXA }, columnWidths: [1800, 2713, 1800, 2713], rows: [new TableRow({ children: [...ic('협정 시작일', today, 1800, 2713), ...ic('협정 갱신일', '매 6개월', 1800, 2713)] }), new TableRow({ children: [...ic('문서 분류', '생활 협정서', 1800, 2713), ...ic('발급 기관', '자취박사', 1800, 2713)] })] }), blank(200))

    // 4. 갈등 분석
    if (summary) ch.push(sh('■ 갈등 분석 및 협정 배경'), new Table({ width: { size: 9026, type: WidthType.DXA }, columnWidths: [9026], rows: [new TableRow({ children: [new TableCell({ borders: ab, shading: { fill: 'FAFAFA', type: ShadingType.CLEAR }, margins: { top: 160, bottom: 160, left: 240, right: 240 }, width: { size: 9026, type: WidthType.DXA }, children: [new Paragraph({ spacing: { line: 360 }, children: [new TextRun({ text: summary, size: 20, color: '374151', font: 'Malgun Gothic' })] })] })] })] }), blank(200))

    // 5. 생활 규칙
    const hr = new TableRow({ tableHeader: true, children: ['No.', '항목', '규칙 내용', '공평한 이유'].map((t, i) => new TableCell({ width: { size: [400, 1200, 4626, 2800][i], type: WidthType.DXA }, shading: { fill: '1E3A5F', type: ShadingType.CLEAR }, borders: ab, margins: { top: 120, bottom: 120, left: 120, right: 120 }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: t, bold: true, size: 19, color: 'FFFFFF', font: 'Malgun Gothic' })] })] })) })
    const rr = (rules || []).map((r: { item: string; rule: string; reason: string }, i: number) => new TableRow({ children: [new TableCell({ width: { size: 400, type: WidthType.DXA }, borders: ab, shading: { fill: i % 2 === 0 ? 'FFFFFF' : 'F8FAFC', type: ShadingType.CLEAR }, margins: { top: 120, bottom: 120, left: 120, right: 120 }, verticalAlign: VerticalAlign.CENTER, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: String(i + 1), bold: true, size: 20, color: '2563EB', font: 'Malgun Gothic' })] })] }), new TableCell({ width: { size: 1200, type: WidthType.DXA }, borders: ab, shading: { fill: i % 2 === 0 ? 'FFFFFF' : 'F8FAFC', type: ShadingType.CLEAR }, margins: { top: 120, bottom: 120, left: 120, right: 120 }, verticalAlign: VerticalAlign.CENTER, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: r.item, bold: true, size: 19, color: '1E3A5F', font: 'Malgun Gothic' })] })] }), new TableCell({ width: { size: 4626, type: WidthType.DXA }, borders: ab, shading: { fill: i % 2 === 0 ? 'FFFFFF' : 'F8FAFC', type: ShadingType.CLEAR }, margins: { top: 120, bottom: 120, left: 160, right: 160 }, children: [new Paragraph({ spacing: { line: 340 }, children: [new TextRun({ text: r.rule, size: 19, color: '1F2937', font: 'Malgun Gothic' })] })] }), new TableCell({ width: { size: 2800, type: WidthType.DXA }, borders: ab, shading: { fill: i % 2 === 0 ? 'FFFFFF' : 'F8FAFC', type: ShadingType.CLEAR }, margins: { top: 120, bottom: 120, left: 160, right: 160 }, children: [new Paragraph({ spacing: { line: 340 }, children: [new TextRun({ text: r.reason, size: 18, color: '6B7280', italics: true, font: 'Malgun Gothic' })] })] })] }))
    ch.push(sh('■ 생활 규칙'), new Table({ width: { size: 9026, type: WidthType.DXA }, columnWidths: [400, 1200, 4626, 2800], rows: [hr, ...rr] }), blank(200))

    // 6. 팁
    if (tips?.length > 0) { ch.push(sh('■ 원활한 공동생활을 위한 팁'), ...(tips as string[]).map((tip, i) => new Paragraph({ spacing: { before: 100, after: 100, line: 360 }, children: [new TextRun({ text: `  ${i + 1}.  `, bold: true, size: 20, color: '2563EB', font: 'Malgun Gothic' }), new TextRun({ text: tip, size: 20, color: '374151', font: 'Malgun Gothic' })] })), blank(160)) }

    // 7. 협정서 본문
    if (agreement) ch.push(sh('■ 생활 협정서 본문'), new Table({ width: { size: 9026, type: WidthType.DXA }, columnWidths: [9026], rows: [new TableRow({ children: [new TableCell({ borders: { top: cb, bottom: cb, left: { style: BorderStyle.THICK, size: 20, color: '2563EB' }, right: nb }, shading: { fill: 'EFF6FF', type: ShadingType.CLEAR }, margins: { top: 200, bottom: 200, left: 300, right: 300 }, width: { size: 9026, type: WidthType.DXA }, children: [new Paragraph({ spacing: { line: 400 }, children: [new TextRun({ text: agreement, size: 21, color: '1E293B', font: 'Malgun Gothic' })] })] })] })] }), blank(300))

    // 8. 서명란
    const sH = new TableRow({ children: ['이름', '기재란', '서명 (인)', '기재란', '작성일'].map((t, i) => new TableCell({ width: { size: [1400, 2400, 1400, 2400, 1426][i], type: WidthType.DXA }, borders: ab, shading: { fill: '1E3A5F', type: ShadingType.CLEAR }, margins: { top: 100, bottom: 100, left: 150, right: 150 }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: t, bold: true, size: 19, color: 'FFFFFF', font: 'Malgun Gothic' })] })] })) })
    const sR = (label: string) => new TableRow({ height: { value: 900, rule: 'atLeast' as const }, children: [new TableCell({ width: { size: 1400, type: WidthType.DXA }, borders: ab, shading: { fill: 'F1F5F9', type: ShadingType.CLEAR }, margins: { top: 120, bottom: 120, left: 150, right: 150 }, verticalAlign: VerticalAlign.CENTER, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: label, bold: true, size: 20, color: '475569', font: 'Malgun Gothic' })] })] }), new TableCell({ width: { size: 2400, type: WidthType.DXA }, borders: ab, margins: { top: 120, bottom: 120, left: 150, right: 150 }, children: [new Paragraph({ children: [new TextRun('')] })] }), new TableCell({ width: { size: 1400, type: WidthType.DXA }, borders: ab, shading: { fill: 'F1F5F9', type: ShadingType.CLEAR }, margins: { top: 120, bottom: 120, left: 150, right: 150 }, verticalAlign: VerticalAlign.CENTER, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: '(인)', size: 18, color: '94A3B8', font: 'Malgun Gothic' })] })] }), new TableCell({ width: { size: 2400, type: WidthType.DXA }, borders: ab, margins: { top: 120, bottom: 120, left: 150, right: 150 }, children: [new Paragraph({ children: [new TextRun('')] })] }), new TableCell({ width: { size: 1426, type: WidthType.DXA }, borders: ab, shading: { fill: 'F1F5F9', type: ShadingType.CLEAR }, margins: { top: 120, bottom: 120, left: 150, right: 150 }, verticalAlign: VerticalAlign.CENTER, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: today, size: 17, color: '94A3B8', font: 'Malgun Gothic' })] })] })] })
    ch.push(sh('■ 서명란'), new Paragraph({ spacing: { before: 0, after: 240, line: 360 }, children: [new TextRun({ text: '위 생활 협정서의 내용을 충분히 숙지하고, 이를 성실히 준수할 것을 서명으로써 확인합니다.', size: 19, color: '475569', font: 'Malgun Gothic' })] }), new Table({ width: { size: 9026, type: WidthType.DXA }, columnWidths: [1400, 2400, 1400, 2400, 1426], rows: [sH, sR('룸메이트 1'), sR('룸메이트 2'), sR('룸메이트 3')] }), blank(300))

    // 9. 하단 고지
    ch.push(new Table({ width: { size: 9026, type: WidthType.DXA }, columnWidths: [9026], borders: { top: { style: BorderStyle.SINGLE, size: 4, color: 'E2E8F0' }, bottom: nb, left: nb, right: nb, insideH: nb, insideV: nb }, rows: [new TableRow({ children: [new TableCell({ borders: nbs, margins: { top: 160, bottom: 0, left: 0, right: 0 }, width: { size: 9026, type: WidthType.DXA }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: '본 협정서는 자취박사에서 자동 생성되었습니다.  |  법적 효력을 갖지 않으며 생활 참고용으로 사용하시기 바랍니다.', size: 16, color: 'CBD5E1', font: 'Malgun Gothic' })] })] })] })] }))

    const doc = new Document({ styles: { default: { document: { run: { font: 'Malgun Gothic', size: 20 } } } }, sections: [{ properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1134, right: 1134, bottom: 1134, left: 1134 } } }, headers: { default: new Header({ children: [new Table({ width: { size: 9638, type: WidthType.DXA }, columnWidths: [7000, 2638], borders: { top: nb, bottom: { style: BorderStyle.SINGLE, size: 4, color: 'E2E8F0' }, left: nb, right: nb, insideH: nb, insideV: nb }, rows: [new TableRow({ children: [new TableCell({ borders: nbs, width: { size: 7000, type: WidthType.DXA }, children: [new Paragraph({ children: [new TextRun({ text: '자취박사  |  룸메이트 생활 협정서', size: 17, color: '94A3B8', font: 'Malgun Gothic' })] })] }), new TableCell({ borders: nbs, width: { size: 2638, type: WidthType.DXA }, children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: [new TextRun({ text: today, size: 17, color: '94A3B8', font: 'Malgun Gothic' })] })] })] })] })] }) }, footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: '- ', size: 17, color: '94A3B8' }), new TextRun({ children: [PageNumber.CURRENT], size: 17, color: '94A3B8' }), new TextRun({ text: ' -', size: 17, color: '94A3B8' })] })] }) }, children: ch }] })
    const buffer = await Packer.toBuffer(doc)
    return new NextResponse(buffer, { headers: { 'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'Content-Disposition': `attachment; filename*=UTF-8''%EB%A3%B8%EB%A9%94%EC%9D%B4%ED%8A%B8_%EC%83%9D%ED%99%9C%ED%98%91%EC%A0%95%EC%84%9C.docx` } })
  } catch (error) {
    console.error('DOCX error:', error)
    return NextResponse.json({ error: '파일 생성에 실패했어요.' }, { status: 500 })
  }
}